version: '3'

services:
  prestashop:
    image: prestashop/prestashop:1.7
    container_name: prestashop
    environment:
      PS_DEV_MODE: 1
      DB_SERVER: db
      DB_NAME: BE_185872_db
      DB_USER: root
      DB_PASSWD: student
    ports:
      - "18587:443"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 60s
      resources:
        limits:
          cpus: '0.5'
          memory: 512M  
    networks:
      - admin-mysql_default

networks:
  admin-mysql_default:
    external: true
