version: '3'

services:
  mysql:
    image: mysql:8
    container_name: prestashop-db
    command: --lower_case_table_names=2
    environment:
      MYSQL_DATABASE: prestashop
      MYSQL_ROOT_PASSWORD: prestashop
    volumes:
      - ./db_dump/mysql:/var/lib/mysql
      - ./db_dump/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - prestashop

  prestashop:
    image: prestashop/prestashop:1.7
    container_name: prestashop
    environment:
      DB_SERVER: mysql
    volumes:
      - ./app:/var/www/html
    ports:
      - 8080:80
    networks:
      - prestashop

networks:
  prestashop:
