version: '3'

      
services:
  mysql:
    image: mariadb:latest
    container_name: prestashop-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      DEV_MODE: ${DEV_MODE:-}
      MYSQL_DATABASE: prestashop
      MYSQL_ROOT_PASSWORD: prestashop
      PHP_VERSION: 7.2
    volumes:
      - ./db_dump/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - prestashop
      

  prestashop:
    image: prestashop/prestashop:1.7
    container_name: prestashop
    environment:
      DB_SERVER: mysql
      PS_DEV_MODE: 1
      
         
    volumes:
      - ./app:/var/www/html
    ports:
      - 8080:80
    networks:
      - prestashop

networks:
  prestashop:
