version: '3'

services:
  mysql:
    image: mariadb:latest
    container_name: prestashop-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: prestashop
      MYSQL_ROOT_PASSWORD: prestashop
      SHOP_HTTP_PORT: ${SHOP_HTTPS_PORT}
      SHOP_HTTPS_PORT: ${SHOP_HTTPS_PORT}

    volumes:
      - ./db_dump/mysql:/var/lib/mysql
    ports:
      - "${MARIADB_PORT}:3306"
    networks:
      - prestashop

  prestashop:
    image: prestashop/prestashop:1.7
    container_name: prestashop
    environment:
      DB_SERVER: mysql
      SHOP_HTTP_PORT: ${SHOP_HTTPS_PORT}
      SHOP_HTTPS_PORT: ${SHOP_HTTPS_PORT}
    volumes:
      - ./app:/var/www/html
    ports:
      - "${SHOP_HTTP_PORT}:80"
      - "${SHOP_HTTPS_PORT}:443"
    networks:
      - prestashop

networks:
  prestashop:
