<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container003z2n6\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container003z2n6/appProdProjectContainer.php') {
    touch(__DIR__.'/Container003z2n6.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container003z2n6\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container003z2n6\appProdProjectContainer([
    'container.build_hash' => '003z2n6',
    'container.build_id' => '3cbf3513',
    'container.build_time' => 1700508815,
], __DIR__.\DIRECTORY_SEPARATOR.'Container003z2n6');
