<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAh2jrvs\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAh2jrvs/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerAh2jrvs.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerAh2jrvs\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerAh2jrvs\appProdProjectContainer([
    'container.build_hash' => 'Ah2jrvs',
    'container.build_id' => 'ae1f9c94',
    'container.build_time' => 1701540893,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAh2jrvs');
