<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCk3fax4\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCk3fax4/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerCk3fax4.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerCk3fax4\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerCk3fax4\appProdProjectContainer([
    'container.build_hash' => 'Ck3fax4',
    'container.build_id' => 'e2bf2d7a',
    'container.build_time' => 1701533540,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCk3fax4');
