<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR72coic\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR72coic/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerR72coic.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerR72coic\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerR72coic\appProdProjectContainer([
    'container.build_hash' => 'R72coic',
    'container.build_id' => 'd251b312',
    'container.build_time' => 1700508989,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR72coic');
