<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9fbjrks\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9fbjrks/appProdProjectContainer.php') {
    touch(__DIR__.'/Container9fbjrks.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container9fbjrks\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container9fbjrks\appProdProjectContainer([
    'container.build_hash' => '9fbjrks',
    'container.build_id' => 'e515d7e9',
    'container.build_time' => 1700517937,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9fbjrks');
